### ISSUE TITLE
stop/start pulse

### ISSUE THREAD

**Issue by junhohong** [ctews/SwiftPulse#11]
Is there a way to stop and restart the pulse?

**Comment by ctews** [comment]
Hey junhohong,

what exactly do you try to achieve? There are several ways to do so or fake that effect. Currently I have no pause and resume method implemented. But you could set the alpha of the animation to zero, set it to hidden, removeAllAnimations of the element that uses that and reattach it again. I can try to implement pause and resume if I get some free time, but won't be able to do it quickly.

**Comment by junhohong** [comment]
I'm trying to activate the pulse on a longtap gesture and remove the pulse when the touch is released.

**Comment by junhohong** [comment]
Do I call removeAllAnimations on the layer it's attached to or the actual imageView? Also, how would I reattach? .insertSublayer?

**Comment by junhohong** [comment]
Thanks for getting back to me so fast btw.

**Comment by ctews** [comment]
Cannot test it in person right now but the whole thing is a subclass of CALayer. So if you keep a reference to the pulsing CALayer you should be able to remove that specific layer from the view it's lying on. Basically on touchRelease you could do pulseReference.removeFromSuperLayer.

That's a guess in the wild, but should work in theory. Let me know!

**Comment by junhohong** [comment]
I've actually tried that and it does successfully remove the pulse. However my problem is starting up the animation again - I've tried initializing the animation again and inserting it to the sublayer, keeping the same animation and inserting it to the sublayer -- both did not work :(

**Comment by ctews** [comment]
That's weird. Could you attach a code example? I would think at least reinirializing it again and add it as a sublayer  should work properly.

**Comment by junhohong** [comment]
On longhold:
```
let pulseEffect = LFTPulseAnimation(repeatCount:Float.infinity, radius:60, position: CGPoint(x:pulseView.frame.width/2,y:pulseView.frame.height/2))
pulseView.layer.insertSublayer(pulseEffect, below: pulseView.layer)
```
On release:
`pulseView.layer.sublayers?.forEach{$0.removeFromSuperlayer()}
`

**Comment by junhohong** [comment]
Exiting and entering the app again makes it work, could be a lead

**Comment by ctews** [comment]
could you please try the following:

Save the reference to the pulse effect and then do the following:
On release:
pulseEffect.removeFromSuperLayer()

So don't traverse through layer hierarchy and remove every sublayer but just the pulseEffect layer.

**Comment by junhohong** [comment]
I've tried that as well, same effect :(

**Comment by ctews** [comment]
I am on the run so can't look deeper into it. But it's a standard CALayer, whatever is wrong there should also not work with a normal CALayer. Did you try it with a simple CALayer if it behaves the same?

**Comment by junhohong** [comment]
Thanks for helping out. I'll try that.

**Comment by junhohong** [comment]
Simple CALayer behaves the same...

**Comment by junhohong** [comment]
Figured it out!!!! One of my other animations was interfering with it for some reason.

**Comment by ctews** [comment]
Happy that you could resolve the problem! Happy coding!
