### ISSUE TITLE
Use of unresolved Identifier 'Async' in LFTPulseAnimation.swift File

### ISSUE THREAD

**Issue by abircse06** [ctews/SwiftPulse#2]
I install the async lib(https://github.com/duemunk/Async) using the cocoaPod and then just add the file from xcode->New->File and the LFTPulseAnimation.swift file and it show me this error . but before adding the LFTPulseAnimation.swift file and right after installing the async lib though Pod , it was working file and project was running properly. Not sure what I am missing here . 

using 
Xcode Version 6.3.1 (6D1002)
Swift 1.2

**Comment by ctews** [comment]
Please make sure that Async gets linked properly from the Pods against the right target. But it has nothing to do with LFTPulseAnimation, since it's just searching for this class ;) Maybe I should just remove the Async dependency and use the standard GCD call.

**Comment by ayalcinkaya** [comment]
change the Async library code with that 

```
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), {
            self.setupAnimationGroup()
            self.setPulseRadius(self.radius)
            
            if (self.pulseInterval != Double.infinity) {
                dispatch_async(dispatch_get_main_queue(), {
                    self.addAnimation(self.animationGroup, forKey: "pulse")
                })
            }
        })
```
