### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by simonbromberg** [ctews/SwiftPulse#3]
Tried replicating what you describe in the readme, no pulse appears. Are there some properties you have to set to get it to show? A demo might help.

EDIT: Looks like the default colour is white, which seems like a strange choice.

**Comment by ctews** [comment]
```swift
self.button = UIButton(frame: CGRect(...))
self.pulseEffect = LFTPulseAnimation(repeatCount: Float.infinity, radius:20, position:self.button!.center)
self.layer.insertSublayer(self.pulseEffect, below: self.hubIcon!.layer)
self.addSubview(self.hubIcon!)
```

Let me know if this helps :)
