### ISSUE TITLE
Any extra tips on how to use it?

### ISSUE THREAD

**Issue by nassarofficial** [ctews/SwiftPulse#5]
Hello, Any extra tips on how to use it? I keep getting unresolved identifier 'pulseEffect'.

**Comment by ctews** [comment]
Could you provide more info? Some code example?

**Comment by nassarofficial** [comment]
Thanks for the fast response :D         

I created an image, and its outlet, and used the code on the readme. 

pulseEffect = LFTPulseAnimation(repeatCount: Float.infinity, radius:20, position:imageView.center)
view.layer.insertSublayer(self.pulseEffect, below: imageView.layer)

**Comment by ctews** [comment]
Well, you should initialize the variable at least ;) so the right code would be:

`let pulseEffect = LFTPulseAnimation(repeatCount: Float.infinity, radius:20, position:imageView.center)`

**Comment by nassarofficial** [comment]
Sorry, my bad, the problem was in the image outlet.
